FROM golang:1.25.0-alpine AS builder

ARG SERVICE=api-gateway
WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY cmd ./cmd
COPY internal ./internal

RUN CGO_ENABLED=0 GOOS=linux go build -o /out/service ./cmd/${SERVICE}

FROM alpine:3.20

ARG SERVICE_PORT=8080
RUN addgroup -S app && adduser -S app -G app
WORKDIR /srv
COPY --from=builder /out/service /usr/local/bin/service

USER app
EXPOSE ${SERVICE_PORT}
ENTRYPOINT ["/usr/local/bin/service"]
