#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BASE_COMPOSE_FILE="${ROOT_DIR}/compose.yaml"
FNN_COMPOSE_FILE="${ROOT_DIR}/compose.fnn.yaml"
USDI_E2E_COMPOSE_FILE="${ROOT_DIR}/compose.usdi-e2e.yaml"
LOG_DIR="$(mktemp -d /tmp/1tok-compose-usdi-e2e-screenshots.XXXXXX)"
ARTIFACT_DIR="${E2E_USDI_SCREENSHOT_OUTPUT_DIR:-${ROOT_DIR}/.artifacts/usdi-e2e}"
mkdir -p "${ARTIFACT_DIR}"
ARTIFACT_DIR="$(cd "${ARTIFACT_DIR}" && pwd)"
CARRIER_REMOTE_KEY_DIR="$(mktemp -d /tmp/1tok-carrier-remote.XXXXXX)"
BUN_VERSION="${BUN_VERSION:-$(grep -o 'bun@[^\"]*' "${ROOT_DIR}/package.json" | cut -d'@' -f2)}"

COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-1tok-usdi-e2e}"
ONE_TOK_EXECUTION_GATEWAY_TOKEN="${ONE_TOK_EXECUTION_GATEWAY_TOKEN:-local-execution-gateway-token}"
ONE_TOK_SETTLEMENT_SERVICE_TOKEN="${ONE_TOK_SETTLEMENT_SERVICE_TOKEN:-local-settlement-service-token}"
ONE_TOK_EXECUTION_EVENT_TOKEN="${ONE_TOK_EXECUTION_EVENT_TOKEN:-local-execution-event-token}"
CARRIER_GATEWAY_API_TOKEN="${CARRIER_GATEWAY_API_TOKEN:-test-gateway-token}"
CARRIER_SERVER_API_TOKEN="${CARRIER_SERVER_API_TOKEN:-test-daemon-token}"
OPENAI_API_KEY="${OPENAI_API_KEY:-}"
OPENAI_CODEX_TOKEN="${OPENAI_CODEX_TOKEN:-}"
OPENAI_BASE_URL="${OPENAI_BASE_URL:-}"
FIBER_APP_ID="${FIBER_APP_ID:-app_1}"
FIBER_HMAC_SECRET="${FIBER_HMAC_SECRET:-replace-me}"
POSTGRES_PUBLISHED_PORT="${POSTGRES_PUBLISHED_PORT:-45432}"
REDIS_PUBLISHED_PORT="${REDIS_PUBLISHED_PORT:-46379}"
NATS_PUBLISHED_PORT="${NATS_PUBLISHED_PORT:-44222}"
NATS_MONITOR_PUBLISHED_PORT="${NATS_MONITOR_PUBLISHED_PORT:-48222}"
IAM_PUBLISHED_PORT="${IAM_PUBLISHED_PORT:-48081}"
API_GATEWAY_PUBLISHED_PORT="${API_GATEWAY_PUBLISHED_PORT:-48080}"
MARKETPLACE_PUBLISHED_PORT="${MARKETPLACE_PUBLISHED_PORT:-48082}"
SETTLEMENT_PUBLISHED_PORT="${SETTLEMENT_PUBLISHED_PORT:-48083}"
EXECUTION_PUBLISHED_PORT="${EXECUTION_PUBLISHED_PORT:-48085}"
WEB_PUBLISHED_PORT="${WEB_PUBLISHED_PORT:-43000}"
FIBER_ADAPTER_PUBLISHED_PORT="${FIBER_ADAPTER_PUBLISHED_PORT:-48091}"
FNN_PUBLISHED_RPC_PORT="${FNN_PUBLISHED_RPC_PORT:-48227}"
FNN_PUBLISHED_P2P_PORT="${FNN_PUBLISHED_P2P_PORT:-48228}"
FNN2_PUBLISHED_RPC_PORT="${FNN2_PUBLISHED_RPC_PORT:-49227}"
FNN2_PUBLISHED_P2P_PORT="${FNN2_PUBLISHED_P2P_PORT:-49228}"
FNN_VERSION="${FNN_VERSION:-v0.6.1}"
FNN_ASSET="${FNN_ASSET:-fnn_v0.6.1-x86_64-linux-portable.tar.gz}"
FNN_ASSET_SHA256="${FNN_ASSET_SHA256:-8f9a69361f662438fa1fc29ddc668192810b13021536ebd1101c84dc0cfa330f}"
FIBER_SECRET_KEY_PASSWORD="${FIBER_SECRET_KEY_PASSWORD:-local-fnn-dev-password}"
FNN_CKB_RPC_URL="${FNN_CKB_RPC_URL:-https://testnet.ckbapp.dev/}"
FNN2_CKB_RPC_URL="${FNN2_CKB_RPC_URL:-${FNN_CKB_RPC_URL}}"
SETTLEMENT_RECONCILER_INTERVAL="${SETTLEMENT_RECONCILER_INTERVAL:-5s}"
CARRIER_E2E_REMOTE_PRIVATE_KEY_PATH="${CARRIER_E2E_REMOTE_PRIVATE_KEY_PATH:-${CARRIER_REMOTE_KEY_DIR}/id_ed25519}"
CARRIER_E2E_REMOTE_AUTHORIZED_KEY="${CARRIER_E2E_REMOTE_AUTHORIZED_KEY:-}"

"${ROOT_DIR}/scripts/prepare-carrier-dep.sh"

prepare_carrier_remote_fixture() {
  if [[ -z "${CARRIER_E2E_REMOTE_AUTHORIZED_KEY}" ]]; then
    ssh-keygen -q -t ed25519 -N '' -f "${CARRIER_E2E_REMOTE_PRIVATE_KEY_PATH}" >/dev/null
    CARRIER_E2E_REMOTE_AUTHORIZED_KEY="$(cat "${CARRIER_E2E_REMOTE_PRIVATE_KEY_PATH}.pub")"
  fi
  chmod 600 "${CARRIER_E2E_REMOTE_PRIVATE_KEY_PATH}" >/dev/null 2>&1 || true
}

prepare_carrier_remote_fixture

compose() {
  (
    cd "${ROOT_DIR}"
    COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME}" \
    ONE_TOK_EXECUTION_GATEWAY_TOKEN="${ONE_TOK_EXECUTION_GATEWAY_TOKEN}" \
    ONE_TOK_SETTLEMENT_SERVICE_TOKEN="${ONE_TOK_SETTLEMENT_SERVICE_TOKEN}" \
    ONE_TOK_EXECUTION_EVENT_TOKEN="${ONE_TOK_EXECUTION_EVENT_TOKEN}" \
    CARRIER_GATEWAY_API_TOKEN="${CARRIER_GATEWAY_API_TOKEN}" \
    CARRIER_SERVER_API_TOKEN="${CARRIER_SERVER_API_TOKEN}" \
    OPENAI_API_KEY="${OPENAI_API_KEY}" \
    OPENAI_CODEX_TOKEN="${OPENAI_CODEX_TOKEN}" \
    OPENAI_BASE_URL="${OPENAI_BASE_URL}" \
    CARRIER_E2E_REMOTE_PRIVATE_KEY_PATH="${CARRIER_E2E_REMOTE_PRIVATE_KEY_PATH}" \
    CARRIER_E2E_REMOTE_AUTHORIZED_KEY="${CARRIER_E2E_REMOTE_AUTHORIZED_KEY}" \
    FIBER_APP_ID="${FIBER_APP_ID}" \
    FIBER_HMAC_SECRET="${FIBER_HMAC_SECRET}" \
    POSTGRES_PUBLISHED_PORT="${POSTGRES_PUBLISHED_PORT}" \
    REDIS_PUBLISHED_PORT="${REDIS_PUBLISHED_PORT}" \
    NATS_PUBLISHED_PORT="${NATS_PUBLISHED_PORT}" \
    NATS_MONITOR_PUBLISHED_PORT="${NATS_MONITOR_PUBLISHED_PORT}" \
    IAM_PUBLISHED_PORT="${IAM_PUBLISHED_PORT}" \
    API_GATEWAY_PUBLISHED_PORT="${API_GATEWAY_PUBLISHED_PORT}" \
    MARKETPLACE_PUBLISHED_PORT="${MARKETPLACE_PUBLISHED_PORT}" \
    SETTLEMENT_PUBLISHED_PORT="${SETTLEMENT_PUBLISHED_PORT}" \
    EXECUTION_PUBLISHED_PORT="${EXECUTION_PUBLISHED_PORT}" \
    WEB_PUBLISHED_PORT="${WEB_PUBLISHED_PORT}" \
    FIBER_ADAPTER_PUBLISHED_PORT="${FIBER_ADAPTER_PUBLISHED_PORT}" \
    FNN_PUBLISHED_RPC_PORT="${FNN_PUBLISHED_RPC_PORT}" \
    FNN_PUBLISHED_P2P_PORT="${FNN_PUBLISHED_P2P_PORT}" \
    FNN2_PUBLISHED_RPC_PORT="${FNN2_PUBLISHED_RPC_PORT}" \
    FNN2_PUBLISHED_P2P_PORT="${FNN2_PUBLISHED_P2P_PORT}" \
    FNN_VERSION="${FNN_VERSION}" \
    FNN_ASSET="${FNN_ASSET}" \
    FNN_ASSET_SHA256="${FNN_ASSET_SHA256}" \
    FIBER_SECRET_KEY_PASSWORD="${FIBER_SECRET_KEY_PASSWORD}" \
    FNN_CKB_RPC_URL="${FNN_CKB_RPC_URL}" \
    FNN2_CKB_RPC_URL="${FNN2_CKB_RPC_URL}" \
    SETTLEMENT_RECONCILER_INTERVAL="${SETTLEMENT_RECONCILER_INTERVAL}" \
    BUN_VERSION="${BUN_VERSION}" \
    E2E_USDI_HOST_OUTPUT_DIR="${ARTIFACT_DIR}" \
    docker compose -f "${BASE_COMPOSE_FILE}" -f "${FNN_COMPOSE_FILE}" -f "${USDI_E2E_COMPOSE_FILE}" "$@"
  )
}

cleanup() {
  local code=$?
  trap - EXIT
  compose logs >"${LOG_DIR}/compose.log" 2>&1 || true
  compose down -v --remove-orphans >/dev/null 2>&1 || true
  docker run --rm -v "${ARTIFACT_DIR}:/artifacts" alpine:3.20 chown -R "$(id -u):$(id -g)" /artifacts >/dev/null 2>&1 || true
  rm -rf "${CARRIER_REMOTE_KEY_DIR}" >/dev/null 2>&1 || true
  if [[ "${code}" -ne 0 ]]; then
    echo "usdi e2e screenshots failed; logs are in ${LOG_DIR}" >&2
    tail -n 400 "${LOG_DIR}/compose.log" >&2 || true
  else
    rm -rf "${LOG_DIR}"
  fi
  echo "usdi e2e screenshot artifacts are in ${ARTIFACT_DIR}"
  exit "${code}"
}
trap cleanup EXIT

wait_for_container() {
  local service="$1"
  local attempts="${2:-180}"
  for ((i = 0; i < attempts; i++)); do
    local container_id
    container_id="$(compose ps -q "${service}" 2>/dev/null || true)"
    if [[ -n "${container_id}" ]]; then
      printf '%s\n' "${container_id}"
      return 0
    fi
    sleep 2
  done
  echo "timed out waiting for ${service} container" >&2
  return 1
}

wait_for_exit() {
  local container_id="$1"
  local label="$2"
  local attempts="${3:-600}"
  for ((i = 0; i < attempts; i++)); do
    local status
    status="$(docker inspect -f '{{.State.Status}}' "${container_id}" 2>/dev/null || true)"
    if [[ "${status}" == "exited" ]]; then
      docker inspect -f '{{.State.ExitCode}}' "${container_id}"
      return 0
    fi
    sleep 2
  done
  echo "timed out waiting for ${label} to exit" >&2
  return 1
}

cd "${ROOT_DIR}"
E2E_USDI_OUTPUT_DIR="${ARTIFACT_DIR}" \
E2E_USDI_KEEP_STACK_UP=1 \
COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME}" \
ONE_TOK_EXECUTION_GATEWAY_TOKEN="${ONE_TOK_EXECUTION_GATEWAY_TOKEN}" \
ONE_TOK_SETTLEMENT_SERVICE_TOKEN="${ONE_TOK_SETTLEMENT_SERVICE_TOKEN}" \
ONE_TOK_EXECUTION_EVENT_TOKEN="${ONE_TOK_EXECUTION_EVENT_TOKEN}" \
CARRIER_GATEWAY_API_TOKEN="${CARRIER_GATEWAY_API_TOKEN}" \
CARRIER_SERVER_API_TOKEN="${CARRIER_SERVER_API_TOKEN}" \
OPENAI_API_KEY="${OPENAI_API_KEY}" \
OPENAI_CODEX_TOKEN="${OPENAI_CODEX_TOKEN}" \
OPENAI_BASE_URL="${OPENAI_BASE_URL}" \
CARRIER_E2E_REMOTE_PRIVATE_KEY_PATH="${CARRIER_E2E_REMOTE_PRIVATE_KEY_PATH}" \
CARRIER_E2E_REMOTE_AUTHORIZED_KEY="${CARRIER_E2E_REMOTE_AUTHORIZED_KEY}" \
FIBER_APP_ID="${FIBER_APP_ID}" \
FIBER_HMAC_SECRET="${FIBER_HMAC_SECRET}" \
POSTGRES_PUBLISHED_PORT="${POSTGRES_PUBLISHED_PORT}" \
REDIS_PUBLISHED_PORT="${REDIS_PUBLISHED_PORT}" \
NATS_PUBLISHED_PORT="${NATS_PUBLISHED_PORT}" \
NATS_MONITOR_PUBLISHED_PORT="${NATS_MONITOR_PUBLISHED_PORT}" \
IAM_PUBLISHED_PORT="${IAM_PUBLISHED_PORT}" \
API_GATEWAY_PUBLISHED_PORT="${API_GATEWAY_PUBLISHED_PORT}" \
MARKETPLACE_PUBLISHED_PORT="${MARKETPLACE_PUBLISHED_PORT}" \
SETTLEMENT_PUBLISHED_PORT="${SETTLEMENT_PUBLISHED_PORT}" \
EXECUTION_PUBLISHED_PORT="${EXECUTION_PUBLISHED_PORT}" \
WEB_PUBLISHED_PORT="${WEB_PUBLISHED_PORT}" \
FIBER_ADAPTER_PUBLISHED_PORT="${FIBER_ADAPTER_PUBLISHED_PORT}" \
FNN_PUBLISHED_RPC_PORT="${FNN_PUBLISHED_RPC_PORT}" \
FNN_PUBLISHED_P2P_PORT="${FNN_PUBLISHED_P2P_PORT}" \
FNN2_PUBLISHED_RPC_PORT="${FNN2_PUBLISHED_RPC_PORT}" \
FNN2_PUBLISHED_P2P_PORT="${FNN2_PUBLISHED_P2P_PORT}" \
FNN_VERSION="${FNN_VERSION}" \
FNN_ASSET="${FNN_ASSET}" \
FNN_ASSET_SHA256="${FNN_ASSET_SHA256}" \
FIBER_SECRET_KEY_PASSWORD="${FIBER_SECRET_KEY_PASSWORD}" \
FNN_CKB_RPC_URL="${FNN_CKB_RPC_URL}" \
FNN2_CKB_RPC_URL="${FNN2_CKB_RPC_URL}" \
SETTLEMENT_RECONCILER_INTERVAL="${SETTLEMENT_RECONCILER_INTERVAL}" \
BUN_VERSION="${BUN_VERSION}" \
./scripts/release-compose-usdi-e2e.sh

compose up -d --build usdi-e2e-screenshot-runner
runner_id="$(wait_for_container usdi-e2e-screenshot-runner)"
exit_code="$(wait_for_exit "${runner_id}" "usdi-e2e-screenshot-runner")"
if [[ "${exit_code}" != "0" ]]; then
  echo "usdi-e2e-screenshot-runner failed with exit code ${exit_code}" >&2
  exit "${exit_code}"
fi
